language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
cache:
  directories:
  - "$HOME/.composer/cache"
env:
  secure: "blngcpQH5JcPY67L8tqabt60Iu0Wy36Pd4HL0zqdFb2L3nGDiAIiEyDhd6PEn+kA0b4qg0P1PF19LBgY2guA9j3bAq1xSBV0FiKNrizqsPdZNNSXuKGddqqHOchGtV8R2hLWzRcTXTaQ5bUJIVKteaepyFRLq6SfTsQoPr6pg94RhXTH3Q5pzM3Lu8gxxWSxdfPGvdvrxtJwUSgCjsHesXIU8YlRlmhe6qvkbqH7p2B1p1WNX/1HP1kVXXZP2Ga8VfvQ8MERlHOKIpR0Nn3p45c5vQEpUunry7D0yIieNtpwJ92ALwrloK28YM/Qbwaxdtja1jJ/o3cbRK8kzU+z3wwK2+tjwH05IX6wRoDqgmOM3vrszCZ8P1rBjuzPXeaVUUPWvrL/PGRBhs/DZWqFu96Y1Tjgd4X2sPNuCv/ZX4y5wIjyKAUMJMZSuXUUgWJ8FZqxgJpCZYA1AjU9M/VNKlnLWtTRCEccbChE2Kmte8yO/S6GCR85l1alVfMYYd4tsyz3UgtC/FjCB+Ar4bMrrrzL6oZMm/N4YIjOGJjS8t+UkGkpYnab3dtOhF7Lbta3mkouv6LlyGaanImLOI4MJ2/Mer92aCnOG50M5kNkjpIXVaRADJ1W9WNw9vi/WkXuJ+XF3mzxzvuYqyG+SAAfr3GM5Neh7X4z6hklI+ncn8s="
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- phpenv config-rm xdebug.ini
install: composer install
script:
- php vendor/bin/phpunit
- php vendor/bin/phpunit --group aws-integration
- "./vendor/bin/phpcs"
after_success:
- vendor/bin/sami.php update phpdoc.php
addons:
  artifacts:
    s3_region: us-east-1
    target_paths: "$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH"
    paths:
    - "./docs/php"
notifications:
  slack:
    rooms:
      secure: "piTlsJVbfpe5zPgEyusCe6yyhvsOBcdbrgOgeiSl9ApoE8WY7r/KbPW77Cly8oj501awm89acCSqdXQXT/6wvUQ85QZ7Iuh+P9MYpm5fsC8XqtJC6Pa1AJdKMafcfHtZWsxqvqFMuxO2XH2sun5IU3+0mrxq4q6we4LTPqEiuA2ofJWUTD+GLRBLRDiShmEXKc+1D0xa4ryf3Og6Sm+CL9fcItkGUuDcEMMz1peGs3EH4vO3vsJ92gp2c0gu2RwJiP1SwtllH5YOeZgo8y1ewwn2Wlt5w/aqH6cJnMgTEHFHECMyJR83idfE4qOYlX2K6MGKvlf/s3lXasI/UPbPnQV15Qd6cLB/8WCBiFgj11cx5OLD2fmgCeho7MgpThhnM3I1xaAshrTg7F13XXGyuam+GrdvrMwQOyVILxDneiZ5FjI4al6JSuk1QVQYea8cprZNpiVE3soQJ9860Ej8bUmBB9EGbrqPxxLsP9vE6n++gMDZszYEmBpFyJrFAA5T6fZ8jvcO1m5+2ehT3WvsDgRH1uo9fWMFMz6EblagEnd1iSkMbJ7yZ+Vl8D4+rhIp99sScYpsSIQc1LDS8pSFE0PH2k5sV9uBmDEdalCW/rrCodfBSK3/BxN0YrxpoEckewtM731jzYlxissUbNsDLKrh7XESTTDpiEv/k6wmv1A="
  on_success: change
  on_failure: always
after_script:
- "php ./docversions.php"