language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
cache:
  directories:
  - "$HOME/.composer/cache"
env:
  secure: "To0YuNVxLMlesLZMbCA9NjoDL09EB58hWyMyzrm+33tf98h9/qrsEtyjRhKPX9jBlqy3gkPpjizlbOGXQN0usvl77UuiXUhu8D7XhQYTgAgOQjYtn5Ff+mvgpPfP6rDnXEaTN/qyIUrAzBbUCXR7lG7LDGeG5zeQZGB7HmOpUegNSjk/Rug9kfZqzKSeoATVC+hvFJsenAvCroG1T4z/2pEDFKbDG4e0Vl7Vu4NVozUhH0p53BTi5HCiA6hNiLyQWhDbAW43MUopx6+Rd0fR+kF58Sa5uRLOL2s6HwU+uUDYYhQ95je2fo6PMPWIgd3mXbdqRnZf32g2fuMJ6fe5he+M2oTRjh1h2BVg1OkKBDtgdiV0gATd3JiE8129kwtW0UNiTqnlrVYtze6T1WDY+t4EF48/nTCI3YLZxvQgZrtxcAliGMs4jePJDc431xBBrgzzKP/Ey+9d7pw5RbdYmXVMm1t6NXM9aHFOJ5dAqK/OByi7TeNd/LIch0PAfVC81iuSNjjLv+mxlm9aWhaPxBc8RKyyPLF5YiAO8le+jok455cM/NTAkDSW4U6SoDaSGqh0lyy9Bn9GcNAepF6X7f9IfRfzdUxO06s6/3ehgH8NoOvmPYE2sBILvdWXfqxXgo6M5ZPTajPRZD0+zsPtrtoCJXWrcZnf+c3VWfWyecw="
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- phpenv config-rm xdebug.ini
install: composer install
script:
- php vendor/bin/phpunit
- php vendor/bin/phpunit --group aws-integration
- "./vendor/bin/phpcs"
after_success:
- vendor/bin/sami.php update phpdoc.php
addons:
  artifacts:
    s3_region: us-east-1
    target_paths: "$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH"
    paths:
    - "./docs/php"
notifications:
  slack:
    rooms:
      secure: "piTlsJVbfpe5zPgEyusCe6yyhvsOBcdbrgOgeiSl9ApoE8WY7r/KbPW77Cly8oj501awm89acCSqdXQXT/6wvUQ85QZ7Iuh+P9MYpm5fsC8XqtJC6Pa1AJdKMafcfHtZWsxqvqFMuxO2XH2sun5IU3+0mrxq4q6we4LTPqEiuA2ofJWUTD+GLRBLRDiShmEXKc+1D0xa4ryf3Og6Sm+CL9fcItkGUuDcEMMz1peGs3EH4vO3vsJ92gp2c0gu2RwJiP1SwtllH5YOeZgo8y1ewwn2Wlt5w/aqH6cJnMgTEHFHECMyJR83idfE4qOYlX2K6MGKvlf/s3lXasI/UPbPnQV15Qd6cLB/8WCBiFgj11cx5OLD2fmgCeho7MgpThhnM3I1xaAshrTg7F13XXGyuam+GrdvrMwQOyVILxDneiZ5FjI4al6JSuk1QVQYea8cprZNpiVE3soQJ9860Ej8bUmBB9EGbrqPxxLsP9vE6n++gMDZszYEmBpFyJrFAA5T6fZ8jvcO1m5+2ehT3WvsDgRH1uo9fWMFMz6EblagEnd1iSkMbJ7yZ+Vl8D4+rhIp99sScYpsSIQc1LDS8pSFE0PH2k5sV9uBmDEdalCW/rrCodfBSK3/BxN0YrxpoEckewtM731jzYlxissUbNsDLKrh7XESTTDpiEv/k6wmv1A="
  on_success: change
  on_failure: always
after_script:
- "php ./docversions.php"